### ISSUE TITLE
Issue with Instance IAM Profile with Windows 2019 AMI

### ISSUE THREAD

**Issue by hcho3** [hcho3/xgboost-devops#11]
See https://serverfault.com/questions/872046/aws-windows-ec2-instance-does-not-recognize-assigned-iam-role. I had to set the Availability Zone and the Subnet of Windows workers to the same as those used for creating the AMI.

**Comment by chyunsu3** [comment]
Fixed in https://github.com/dmlc/xgboost/pull/8142. As long as we use EC2 Image Builder service, we don't have this problem.
