### ISSUE TITLE
Do not trigger builds on pull requests unless explicitly requested by committers

### ISSUE THREAD

**Issue by hcho3** [hcho3/xgboost-devops#9]
See dmlc/xgboost#5176. Right now, every pull request (and edits made to them) will trigger a build in the CI server. Many pull requests are Work In Progress (WIP) and require further edits before a maintainer can merge them. To save cloud costs, no build should run on pull requests unless explicitly requested by a maintainer.

- [ ] Write a Probot app to look for keyword "ok to test" from a maintainer. There should be a database to store the list of pull requests marked as "okay to test"
- [ ] Modify Jenkins runner to query the database mentioned above.

**Comment by chyunsu3** [comment]
With dmlc/xgboost#5884, it should now be easier to do this.

**Comment by chyunsu3** [comment]
Fixed in https://github.com/dmlc/xgboost/pull/8142
